<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="dslab.client.MessageClientMailboxTest" tests="2" skipped="0" failures="2" errors="0" timestamp="2022-12-04T17:52:22" hostname="Jonathans-MacBook-Air.local" time="14.188">
  <properties/>
  <testcase name="inbox_mulipleMails_showsAllInboxDataCorrectly" classname="dslab.client.MessageClientMailboxTest" time="8.125">
    <failure message="java.lang.AssertionError: Expected mailbox server to implement DMTP2.0&#10;Expected: is &quot;ok DMTP2.0&quot;&#10;     but: was &quot;ok DMTP&quot;" type="java.lang.AssertionError">java.lang.AssertionError: Expected mailbox server to implement DMTP2.0
Expected: is &quot;ok DMTP2.0&quot;
     but: was &quot;ok DMTP&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;ok&quot;&#10;     but: was &quot;error invalid Request&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;ok&quot;
     but: was &quot;error invalid Request&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:120)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: is &quot;ok DMTP2.0&quot;&#10;     but: was &quot;ok DMTP&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: is &quot;ok DMTP2.0&quot;
     but: was &quot;ok DMTP&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;ok&quot;&#10;     but: was &quot;error invalid Request&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;ok&quot;
     but: was &quot;error invalid Request&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:120)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: is &quot;ok DMTP2.0&quot;&#10;     but: was &quot;ok DMTP&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: is &quot;ok DMTP2.0&quot;
     but: was &quot;ok DMTP&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;ok&quot;&#10;     but: was &quot;error invalid Request&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;ok&quot;
     but: was &quot;error invalid Request&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:120)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: inbox output did not contain all data from first mail&#10;Expected: (a string containing &quot;trillian@earth.planet&quot; and a string containing &quot;arthur@earth.planet&quot; and a string containing &quot;somesubject&quot; and a string containing &quot;somedata&quot;)&#10;     but: a string containing &quot;trillian@earth.planet&quot; was &quot;&quot;" type="java.lang.AssertionError">java.lang.AssertionError: inbox output did not contain all data from first mail
Expected: (a string containing &quot;trillian@earth.planet&quot; and a string containing &quot;arthur@earth.planet&quot; and a string containing &quot;somesubject&quot; and a string containing &quot;somedata&quot;)
     but: a string containing &quot;trillian@earth.planet&quot; was &quot;&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: inbox output did not contain all data from second mail&#10;Expected: (a string containing &quot;zaphod@univer.ze&quot; and a string containing &quot;zaphodsubject&quot; and a string containing &quot;zaphoddata&quot;)&#10;     but: a string containing &quot;zaphod@univer.ze&quot; was &quot;&quot;" type="java.lang.AssertionError">java.lang.AssertionError: inbox output did not contain all data from second mail
Expected: (a string containing &quot;zaphod@univer.ze&quot; and a string containing &quot;zaphodsubject&quot; and a string containing &quot;zaphoddata&quot;)
     but: a string containing &quot;zaphod@univer.ze&quot; was &quot;&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at dslab.client.MessageClientMailboxTest.inbox_mulipleMails_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="inbox_singleMail_showsAllInboxDataCorrectly" classname="dslab.client.MessageClientMailboxTest" time="6.053">
    <failure message="java.lang.AssertionError: Expected mailbox server to implement DMTP2.0&#10;Expected: is &quot;ok DMTP2.0&quot;&#10;     but: was &quot;ok DMTP&quot;" type="java.lang.AssertionError">java.lang.AssertionError: Expected mailbox server to implement DMTP2.0
Expected: is &quot;ok DMTP2.0&quot;
     but: was &quot;ok DMTP&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at dslab.client.MessageClientMailboxTest.inbox_singleMail_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;ok&quot;&#10;     but: was &quot;error invalid Request&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;ok&quot;
     but: was &quot;error invalid Request&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:120)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.client.MessageClientMailboxTest.inbox_singleMail_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
    <failure message="java.lang.AssertionError: &#10;Expected: (a string containing &quot;trillian@earth.planet&quot; and a string containing &quot;arthur@earth.planet&quot; and a string containing &quot;somesubject&quot; and a string containing &quot;somedata&quot;)&#10;     but: a string containing &quot;trillian@earth.planet&quot; was &quot;&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: (a string containing &quot;trillian@earth.planet&quot; and a string containing &quot;arthur@earth.planet&quot; and a string containing &quot;somesubject&quot; and a string containing &quot;somedata&quot;)
     but: a string containing &quot;trillian@earth.planet&quot; was &quot;&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.client.MessageClientMailboxTest.inbox_singleMail_showsAllInboxDataCorrectly(MessageClientMailboxTest.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <system-out><![CDATA[Exiting the shell, bye!
Exiting the shell, bye!
]]></system-out>
  <system-err><![CDATA[Dec 04, 2022 6:52:22 PM dslab.client.MessageClientMailboxTest setUp
INFO: Creating mailbox server
Dec 04, 2022 6:52:22 PM dslab.client.MessageClientMailboxTest setUp
INFO: Waiting for mailbox server sockets
Dec 04, 2022 6:52:22 PM dslab.mailbox.MailboxServer run
INFO: Server is up!
Dec 04, 2022 6:52:22 PM dslab.client.MessageClientMailboxTest setUp
INFO: Starting message client
Dec 04, 2022 6:52:22 PM dslab.mailbox.ClientCommunicator readLine
SEVERE: Connection reset
Dec 04, 2022 6:52:22 PM dslab.mailbox.ClientCommunicator readLine
SEVERE: Connection reset
Dec 04, 2022 6:52:25 PM dslab.mailbox.MessageStorage put
INFO: put:(user: trillian value: Email{from='arthur@earth.planet', to='trillian@earth.planet', subject='somesubject', data='somedata', domains='null'})
Dec 04, 2022 6:52:25 PM dslab.mailbox.MessageStorage put
INFO: put:(user: trillian value: Email{from='zaphod@univer.ze', to='trillian@earth.planet', subject='zaphodsubject', data='zaphoddata', domains='null'})
Dec 04, 2022 6:52:25 PM dslab.mailbox.MessageStorage put
INFO: put:(user: arthur value: Email{from='zaphod@univer.ze', to='arthur@earth.planet', subject='nottrilliansubject', data='nottrilliandata', domains='null'})
Dec 04, 2022 6:52:30 PM dslab.mailbox.ClientCommunicator establishConnection
SEVERE: SocketException while handling socket: Socket closed
Dec 04, 2022 6:52:30 PM dslab.mailbox.ClientCommunicator establishConnection
SEVERE: SocketException while handling socket: Socket closed
Dec 04, 2022 6:52:30 PM dslab.client.MessageClientMailboxTest setUp
INFO: Creating mailbox server
Dec 04, 2022 6:52:30 PM dslab.client.MessageClientMailboxTest setUp
INFO: Waiting for mailbox server sockets
Dec 04, 2022 6:52:30 PM dslab.mailbox.MailboxServer run
INFO: Server is up!
Dec 04, 2022 6:52:30 PM dslab.client.MessageClientMailboxTest setUp
INFO: Starting message client
Dec 04, 2022 6:52:30 PM dslab.mailbox.ClientCommunicator readLine
SEVERE: Connection reset
Dec 04, 2022 6:52:33 PM dslab.mailbox.MessageStorage put
INFO: put:(user: trillian value: Email{from='arthur@earth.planet', to='trillian@earth.planet', subject='somesubject', data='somedata', domains='null'})
Dec 04, 2022 6:52:36 PM dslab.mailbox.ClientCommunicator establishConnection
SEVERE: SocketException while handling socket: Socket closed
]]></system-err>
</testsuite>
